# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Caleb Waldorf
tagline:             The Website of Caleb Waldorf
description:         The Website of Caleb Waldorf
url:                 http://calebwaldorf.net
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Caleb Waldorf
  url:               https://twitter.com/calebwaldorf
  email:             thereisnothinglesspassive@gmail.com

# Custom vars
version:             1.0.0
